#!/usr/bin/env python3

"""Command Line Interface of AES project.

TODO
"""
import argparse


# import aes.models
# aes.models.main()

# import aes.models_lstm
# aes.models_lstm.main()

# import aes.viz_tsne
# aes.viz_tsne.main()

# import aes.models_cnn_attention
# aes.models_cnn_attention.main()

import aes.models_lstm_attention
aes.models_lstm_attention.main()
